/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IndexedUniswapRouterMinterInterface extends ethers.utils.Interface {
  functions: {
    "factory()": FunctionFragment;
    "swapETHForAllTokensAndMintExact(address,address[],uint256)": FunctionFragment;
    "swapETHForTokensAndMintExact(address[],address,uint256)": FunctionFragment;
    "swapExactETHForTokensAndMint(address[],address,uint256)": FunctionFragment;
    "swapExactTokensForTokensAndMint(uint256,address[],address,uint256)": FunctionFragment;
    "swapTokensForAllTokensAndMintExact(address,uint256,address[],address,uint256)": FunctionFragment;
    "swapTokensForTokensAndMintExact(uint256,address[],address,uint256)": FunctionFragment;
    "weth()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "swapETHForAllTokensAndMintExact",
    values: [string, string[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapETHForTokensAndMintExact",
    values: [string[], string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapExactETHForTokensAndMint",
    values: [string[], string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapExactTokensForTokensAndMint",
    values: [BigNumberish, string[], string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapTokensForAllTokensAndMintExact",
    values: [string, BigNumberish, string[], string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapTokensForTokensAndMintExact",
    values: [BigNumberish, string[], string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "weth", values?: undefined): string;

  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "swapETHForAllTokensAndMintExact",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapETHForTokensAndMintExact",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapExactETHForTokensAndMint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapExactTokensForTokensAndMint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapTokensForAllTokensAndMintExact",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapTokensForTokensAndMintExact",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "weth", data: BytesLike): Result;

  events: {};
}

export class IndexedUniswapRouterMinter extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IndexedUniswapRouterMinterInterface;

  functions: {
    factory(overrides?: CallOverrides): Promise<[string]>;

    swapETHForAllTokensAndMintExact(
      indexPool: string,
      intermediaries: string[],
      poolAmountOut: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swapETHForTokensAndMintExact(
      path: string[],
      indexPool: string,
      poolAmountOut: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swapExactETHForTokensAndMint(
      path: string[],
      indexPool: string,
      minPoolAmountOut: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swapExactTokensForTokensAndMint(
      amountIn: BigNumberish,
      path: string[],
      indexPool: string,
      minPoolAmountOut: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swapTokensForAllTokensAndMintExact(
      tokenIn: string,
      amountInMax: BigNumberish,
      intermediaries: string[],
      indexPool: string,
      poolAmountOut: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swapTokensForTokensAndMintExact(
      amountInMax: BigNumberish,
      path: string[],
      indexPool: string,
      poolAmountOut: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    weth(overrides?: CallOverrides): Promise<[string]>;
  };

  factory(overrides?: CallOverrides): Promise<string>;

  swapETHForAllTokensAndMintExact(
    indexPool: string,
    intermediaries: string[],
    poolAmountOut: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swapETHForTokensAndMintExact(
    path: string[],
    indexPool: string,
    poolAmountOut: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swapExactETHForTokensAndMint(
    path: string[],
    indexPool: string,
    minPoolAmountOut: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swapExactTokensForTokensAndMint(
    amountIn: BigNumberish,
    path: string[],
    indexPool: string,
    minPoolAmountOut: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swapTokensForAllTokensAndMintExact(
    tokenIn: string,
    amountInMax: BigNumberish,
    intermediaries: string[],
    indexPool: string,
    poolAmountOut: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swapTokensForTokensAndMintExact(
    amountInMax: BigNumberish,
    path: string[],
    indexPool: string,
    poolAmountOut: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  weth(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    factory(overrides?: CallOverrides): Promise<string>;

    swapETHForAllTokensAndMintExact(
      indexPool: string,
      intermediaries: string[],
      poolAmountOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swapETHForTokensAndMintExact(
      path: string[],
      indexPool: string,
      poolAmountOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    swapExactETHForTokensAndMint(
      path: string[],
      indexPool: string,
      minPoolAmountOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swapExactTokensForTokensAndMint(
      amountIn: BigNumberish,
      path: string[],
      indexPool: string,
      minPoolAmountOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swapTokensForAllTokensAndMintExact(
      tokenIn: string,
      amountInMax: BigNumberish,
      intermediaries: string[],
      indexPool: string,
      poolAmountOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swapTokensForTokensAndMintExact(
      amountInMax: BigNumberish,
      path: string[],
      indexPool: string,
      poolAmountOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    weth(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    factory(overrides?: CallOverrides): Promise<BigNumber>;

    swapETHForAllTokensAndMintExact(
      indexPool: string,
      intermediaries: string[],
      poolAmountOut: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swapETHForTokensAndMintExact(
      path: string[],
      indexPool: string,
      poolAmountOut: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swapExactETHForTokensAndMint(
      path: string[],
      indexPool: string,
      minPoolAmountOut: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swapExactTokensForTokensAndMint(
      amountIn: BigNumberish,
      path: string[],
      indexPool: string,
      minPoolAmountOut: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swapTokensForAllTokensAndMintExact(
      tokenIn: string,
      amountInMax: BigNumberish,
      intermediaries: string[],
      indexPool: string,
      poolAmountOut: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swapTokensForTokensAndMintExact(
      amountInMax: BigNumberish,
      path: string[],
      indexPool: string,
      poolAmountOut: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    weth(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    factory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    swapETHForAllTokensAndMintExact(
      indexPool: string,
      intermediaries: string[],
      poolAmountOut: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swapETHForTokensAndMintExact(
      path: string[],
      indexPool: string,
      poolAmountOut: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swapExactETHForTokensAndMint(
      path: string[],
      indexPool: string,
      minPoolAmountOut: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swapExactTokensForTokensAndMint(
      amountIn: BigNumberish,
      path: string[],
      indexPool: string,
      minPoolAmountOut: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swapTokensForAllTokensAndMintExact(
      tokenIn: string,
      amountInMax: BigNumberish,
      intermediaries: string[],
      indexPool: string,
      poolAmountOut: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swapTokensForTokensAndMintExact(
      amountInMax: BigNumberish,
      path: string[],
      indexPool: string,
      poolAmountOut: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    weth(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
