/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IndexedNarwhalRouterInterface extends ethers.utils.Interface {
  functions: {
    "burnAndSwapForExactETH(address,uint256,bytes32[],uint256)": FunctionFragment;
    "burnAndSwapForExactTokens(address,uint256,bytes32[],uint256)": FunctionFragment;
    "burnExactAndSwapForETH(address,uint256,bytes32[],uint256)": FunctionFragment;
    "burnExactAndSwapForTokens(address,uint256,bytes32[],uint256)": FunctionFragment;
    "burnForAllTokensAndSwapForETH(address,uint256[],bytes32[],uint256,uint256)": FunctionFragment;
    "burnForAllTokensAndSwapForTokens(address,uint256[],bytes32[],uint256,address,uint256)": FunctionFragment;
    "sushiswapFactory()": FunctionFragment;
    "swapETHForAllTokensAndMintExact(address,bytes32[],uint256)": FunctionFragment;
    "swapETHForExactTokens(uint256,bytes32[],address,uint256)": FunctionFragment;
    "swapETHForTokensAndMintExact(bytes32[],address,uint256)": FunctionFragment;
    "swapExactETHForTokens(uint256,bytes32[],address,uint256)": FunctionFragment;
    "swapExactETHForTokensAndMint(bytes32[],address,uint256)": FunctionFragment;
    "swapExactTokensForETH(uint256,uint256,bytes32[],address,uint256)": FunctionFragment;
    "swapExactTokensForTokens(uint256,uint256,bytes32[],address,uint256)": FunctionFragment;
    "swapExactTokensForTokensAndMint(uint256,bytes32[],address,uint256)": FunctionFragment;
    "swapTokensForAllTokensAndMintExact(address,bytes32[],uint256,address,uint256)": FunctionFragment;
    "swapTokensForExactETH(uint256,uint256,bytes32[],address,uint256)": FunctionFragment;
    "swapTokensForExactTokens(uint256,uint256,bytes32[],address,uint256)": FunctionFragment;
    "swapTokensForTokensAndMintExact(uint256,bytes32[],address,uint256)": FunctionFragment;
    "uniswapFactory()": FunctionFragment;
    "weth()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "burnAndSwapForExactETH",
    values: [string, BigNumberish, BytesLike[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "burnAndSwapForExactTokens",
    values: [string, BigNumberish, BytesLike[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "burnExactAndSwapForETH",
    values: [string, BigNumberish, BytesLike[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "burnExactAndSwapForTokens",
    values: [string, BigNumberish, BytesLike[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "burnForAllTokensAndSwapForETH",
    values: [string, BigNumberish[], BytesLike[], BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "burnForAllTokensAndSwapForTokens",
    values: [
      string,
      BigNumberish[],
      BytesLike[],
      BigNumberish,
      string,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "sushiswapFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "swapETHForAllTokensAndMintExact",
    values: [string, BytesLike[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapETHForExactTokens",
    values: [BigNumberish, BytesLike[], string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapETHForTokensAndMintExact",
    values: [BytesLike[], string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapExactETHForTokens",
    values: [BigNumberish, BytesLike[], string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapExactETHForTokensAndMint",
    values: [BytesLike[], string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapExactTokensForETH",
    values: [BigNumberish, BigNumberish, BytesLike[], string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapExactTokensForTokens",
    values: [BigNumberish, BigNumberish, BytesLike[], string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapExactTokensForTokensAndMint",
    values: [BigNumberish, BytesLike[], string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapTokensForAllTokensAndMintExact",
    values: [string, BytesLike[], BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapTokensForExactETH",
    values: [BigNumberish, BigNumberish, BytesLike[], string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapTokensForExactTokens",
    values: [BigNumberish, BigNumberish, BytesLike[], string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapTokensForTokensAndMintExact",
    values: [BigNumberish, BytesLike[], string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "uniswapFactory",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "weth", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "burnAndSwapForExactETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "burnAndSwapForExactTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "burnExactAndSwapForETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "burnExactAndSwapForTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "burnForAllTokensAndSwapForETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "burnForAllTokensAndSwapForTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sushiswapFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapETHForAllTokensAndMintExact",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapETHForExactTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapETHForTokensAndMintExact",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapExactETHForTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapExactETHForTokensAndMint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapExactTokensForETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapExactTokensForTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapExactTokensForTokensAndMint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapTokensForAllTokensAndMintExact",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapTokensForExactETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapTokensForExactTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapTokensForTokensAndMintExact",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uniswapFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "weth", data: BytesLike): Result;

  events: {};
}

export class IndexedNarwhalRouter extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IndexedNarwhalRouterInterface;

  functions: {
    burnAndSwapForExactETH(
      indexPool: string,
      poolAmountInMax: BigNumberish,
      path: BytesLike[],
      ethAmountOut: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    burnAndSwapForExactTokens(
      indexPool: string,
      poolAmountInMax: BigNumberish,
      path: BytesLike[],
      tokenAmountOut: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    burnExactAndSwapForETH(
      indexPool: string,
      poolAmountIn: BigNumberish,
      path: BytesLike[],
      minAmountOut: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    burnExactAndSwapForTokens(
      indexPool: string,
      poolAmountIn: BigNumberish,
      path: BytesLike[],
      minAmountOut: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    burnForAllTokensAndSwapForETH(
      indexPool: string,
      minAmountsOut: BigNumberish[],
      intermediaries: BytesLike[],
      poolAmountIn: BigNumberish,
      minAmountOut: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    burnForAllTokensAndSwapForTokens(
      indexPool: string,
      minAmountsOut: BigNumberish[],
      intermediaries: BytesLike[],
      poolAmountIn: BigNumberish,
      tokenOut: string,
      minAmountOut: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    sushiswapFactory(overrides?: CallOverrides): Promise<[string]>;

    swapETHForAllTokensAndMintExact(
      indexPool: string,
      intermediaries: BytesLike[],
      poolAmountOut: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swapETHForExactTokens(
      amountOut: BigNumberish,
      path: BytesLike[],
      to: string,
      deadline: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swapETHForTokensAndMintExact(
      path: BytesLike[],
      indexPool: string,
      poolAmountOut: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swapExactETHForTokens(
      amountOutMin: BigNumberish,
      path: BytesLike[],
      to: string,
      deadline: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swapExactETHForTokensAndMint(
      path: BytesLike[],
      indexPool: string,
      minPoolAmountOut: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swapExactTokensForETH(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      path: BytesLike[],
      to: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swapExactTokensForTokens(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      path: BytesLike[],
      to: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swapExactTokensForTokensAndMint(
      amountIn: BigNumberish,
      path: BytesLike[],
      indexPool: string,
      minPoolAmountOut: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swapTokensForAllTokensAndMintExact(
      indexPool: string,
      intermediaries: BytesLike[],
      poolAmountOut: BigNumberish,
      tokenIn: string,
      amountInMax: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swapTokensForExactETH(
      amountOut: BigNumberish,
      amountInMax: BigNumberish,
      path: BytesLike[],
      to: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swapTokensForExactTokens(
      amountOut: BigNumberish,
      amountInMax: BigNumberish,
      path: BytesLike[],
      to: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swapTokensForTokensAndMintExact(
      amountInMax: BigNumberish,
      path: BytesLike[],
      indexPool: string,
      poolAmountOut: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    uniswapFactory(overrides?: CallOverrides): Promise<[string]>;

    weth(overrides?: CallOverrides): Promise<[string]>;
  };

  burnAndSwapForExactETH(
    indexPool: string,
    poolAmountInMax: BigNumberish,
    path: BytesLike[],
    ethAmountOut: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  burnAndSwapForExactTokens(
    indexPool: string,
    poolAmountInMax: BigNumberish,
    path: BytesLike[],
    tokenAmountOut: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  burnExactAndSwapForETH(
    indexPool: string,
    poolAmountIn: BigNumberish,
    path: BytesLike[],
    minAmountOut: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  burnExactAndSwapForTokens(
    indexPool: string,
    poolAmountIn: BigNumberish,
    path: BytesLike[],
    minAmountOut: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  burnForAllTokensAndSwapForETH(
    indexPool: string,
    minAmountsOut: BigNumberish[],
    intermediaries: BytesLike[],
    poolAmountIn: BigNumberish,
    minAmountOut: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  burnForAllTokensAndSwapForTokens(
    indexPool: string,
    minAmountsOut: BigNumberish[],
    intermediaries: BytesLike[],
    poolAmountIn: BigNumberish,
    tokenOut: string,
    minAmountOut: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  sushiswapFactory(overrides?: CallOverrides): Promise<string>;

  swapETHForAllTokensAndMintExact(
    indexPool: string,
    intermediaries: BytesLike[],
    poolAmountOut: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swapETHForExactTokens(
    amountOut: BigNumberish,
    path: BytesLike[],
    to: string,
    deadline: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swapETHForTokensAndMintExact(
    path: BytesLike[],
    indexPool: string,
    poolAmountOut: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swapExactETHForTokens(
    amountOutMin: BigNumberish,
    path: BytesLike[],
    to: string,
    deadline: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swapExactETHForTokensAndMint(
    path: BytesLike[],
    indexPool: string,
    minPoolAmountOut: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swapExactTokensForETH(
    amountIn: BigNumberish,
    amountOutMin: BigNumberish,
    path: BytesLike[],
    to: string,
    deadline: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swapExactTokensForTokens(
    amountIn: BigNumberish,
    amountOutMin: BigNumberish,
    path: BytesLike[],
    to: string,
    deadline: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swapExactTokensForTokensAndMint(
    amountIn: BigNumberish,
    path: BytesLike[],
    indexPool: string,
    minPoolAmountOut: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swapTokensForAllTokensAndMintExact(
    indexPool: string,
    intermediaries: BytesLike[],
    poolAmountOut: BigNumberish,
    tokenIn: string,
    amountInMax: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swapTokensForExactETH(
    amountOut: BigNumberish,
    amountInMax: BigNumberish,
    path: BytesLike[],
    to: string,
    deadline: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swapTokensForExactTokens(
    amountOut: BigNumberish,
    amountInMax: BigNumberish,
    path: BytesLike[],
    to: string,
    deadline: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swapTokensForTokensAndMintExact(
    amountInMax: BigNumberish,
    path: BytesLike[],
    indexPool: string,
    poolAmountOut: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  uniswapFactory(overrides?: CallOverrides): Promise<string>;

  weth(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    burnAndSwapForExactETH(
      indexPool: string,
      poolAmountInMax: BigNumberish,
      path: BytesLike[],
      ethAmountOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    burnAndSwapForExactTokens(
      indexPool: string,
      poolAmountInMax: BigNumberish,
      path: BytesLike[],
      tokenAmountOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    burnExactAndSwapForETH(
      indexPool: string,
      poolAmountIn: BigNumberish,
      path: BytesLike[],
      minAmountOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    burnExactAndSwapForTokens(
      indexPool: string,
      poolAmountIn: BigNumberish,
      path: BytesLike[],
      minAmountOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    burnForAllTokensAndSwapForETH(
      indexPool: string,
      minAmountsOut: BigNumberish[],
      intermediaries: BytesLike[],
      poolAmountIn: BigNumberish,
      minAmountOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    burnForAllTokensAndSwapForTokens(
      indexPool: string,
      minAmountsOut: BigNumberish[],
      intermediaries: BytesLike[],
      poolAmountIn: BigNumberish,
      tokenOut: string,
      minAmountOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    sushiswapFactory(overrides?: CallOverrides): Promise<string>;

    swapETHForAllTokensAndMintExact(
      indexPool: string,
      intermediaries: BytesLike[],
      poolAmountOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swapETHForExactTokens(
      amountOut: BigNumberish,
      path: BytesLike[],
      to: string,
      deadline: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    swapETHForTokensAndMintExact(
      path: BytesLike[],
      indexPool: string,
      poolAmountOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    swapExactETHForTokens(
      amountOutMin: BigNumberish,
      path: BytesLike[],
      to: string,
      deadline: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    swapExactETHForTokensAndMint(
      path: BytesLike[],
      indexPool: string,
      minPoolAmountOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swapExactTokensForETH(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      path: BytesLike[],
      to: string,
      deadline: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    swapExactTokensForTokens(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      path: BytesLike[],
      to: string,
      deadline: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    swapExactTokensForTokensAndMint(
      amountIn: BigNumberish,
      path: BytesLike[],
      indexPool: string,
      minPoolAmountOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swapTokensForAllTokensAndMintExact(
      indexPool: string,
      intermediaries: BytesLike[],
      poolAmountOut: BigNumberish,
      tokenIn: string,
      amountInMax: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swapTokensForExactETH(
      amountOut: BigNumberish,
      amountInMax: BigNumberish,
      path: BytesLike[],
      to: string,
      deadline: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    swapTokensForExactTokens(
      amountOut: BigNumberish,
      amountInMax: BigNumberish,
      path: BytesLike[],
      to: string,
      deadline: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    swapTokensForTokensAndMintExact(
      amountInMax: BigNumberish,
      path: BytesLike[],
      indexPool: string,
      poolAmountOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    uniswapFactory(overrides?: CallOverrides): Promise<string>;

    weth(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    burnAndSwapForExactETH(
      indexPool: string,
      poolAmountInMax: BigNumberish,
      path: BytesLike[],
      ethAmountOut: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    burnAndSwapForExactTokens(
      indexPool: string,
      poolAmountInMax: BigNumberish,
      path: BytesLike[],
      tokenAmountOut: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    burnExactAndSwapForETH(
      indexPool: string,
      poolAmountIn: BigNumberish,
      path: BytesLike[],
      minAmountOut: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    burnExactAndSwapForTokens(
      indexPool: string,
      poolAmountIn: BigNumberish,
      path: BytesLike[],
      minAmountOut: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    burnForAllTokensAndSwapForETH(
      indexPool: string,
      minAmountsOut: BigNumberish[],
      intermediaries: BytesLike[],
      poolAmountIn: BigNumberish,
      minAmountOut: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    burnForAllTokensAndSwapForTokens(
      indexPool: string,
      minAmountsOut: BigNumberish[],
      intermediaries: BytesLike[],
      poolAmountIn: BigNumberish,
      tokenOut: string,
      minAmountOut: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    sushiswapFactory(overrides?: CallOverrides): Promise<BigNumber>;

    swapETHForAllTokensAndMintExact(
      indexPool: string,
      intermediaries: BytesLike[],
      poolAmountOut: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swapETHForExactTokens(
      amountOut: BigNumberish,
      path: BytesLike[],
      to: string,
      deadline: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swapETHForTokensAndMintExact(
      path: BytesLike[],
      indexPool: string,
      poolAmountOut: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swapExactETHForTokens(
      amountOutMin: BigNumberish,
      path: BytesLike[],
      to: string,
      deadline: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swapExactETHForTokensAndMint(
      path: BytesLike[],
      indexPool: string,
      minPoolAmountOut: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swapExactTokensForETH(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      path: BytesLike[],
      to: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swapExactTokensForTokens(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      path: BytesLike[],
      to: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swapExactTokensForTokensAndMint(
      amountIn: BigNumberish,
      path: BytesLike[],
      indexPool: string,
      minPoolAmountOut: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swapTokensForAllTokensAndMintExact(
      indexPool: string,
      intermediaries: BytesLike[],
      poolAmountOut: BigNumberish,
      tokenIn: string,
      amountInMax: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swapTokensForExactETH(
      amountOut: BigNumberish,
      amountInMax: BigNumberish,
      path: BytesLike[],
      to: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swapTokensForExactTokens(
      amountOut: BigNumberish,
      amountInMax: BigNumberish,
      path: BytesLike[],
      to: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swapTokensForTokensAndMintExact(
      amountInMax: BigNumberish,
      path: BytesLike[],
      indexPool: string,
      poolAmountOut: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    uniswapFactory(overrides?: CallOverrides): Promise<BigNumber>;

    weth(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    burnAndSwapForExactETH(
      indexPool: string,
      poolAmountInMax: BigNumberish,
      path: BytesLike[],
      ethAmountOut: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    burnAndSwapForExactTokens(
      indexPool: string,
      poolAmountInMax: BigNumberish,
      path: BytesLike[],
      tokenAmountOut: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    burnExactAndSwapForETH(
      indexPool: string,
      poolAmountIn: BigNumberish,
      path: BytesLike[],
      minAmountOut: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    burnExactAndSwapForTokens(
      indexPool: string,
      poolAmountIn: BigNumberish,
      path: BytesLike[],
      minAmountOut: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    burnForAllTokensAndSwapForETH(
      indexPool: string,
      minAmountsOut: BigNumberish[],
      intermediaries: BytesLike[],
      poolAmountIn: BigNumberish,
      minAmountOut: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    burnForAllTokensAndSwapForTokens(
      indexPool: string,
      minAmountsOut: BigNumberish[],
      intermediaries: BytesLike[],
      poolAmountIn: BigNumberish,
      tokenOut: string,
      minAmountOut: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    sushiswapFactory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    swapETHForAllTokensAndMintExact(
      indexPool: string,
      intermediaries: BytesLike[],
      poolAmountOut: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swapETHForExactTokens(
      amountOut: BigNumberish,
      path: BytesLike[],
      to: string,
      deadline: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swapETHForTokensAndMintExact(
      path: BytesLike[],
      indexPool: string,
      poolAmountOut: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swapExactETHForTokens(
      amountOutMin: BigNumberish,
      path: BytesLike[],
      to: string,
      deadline: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swapExactETHForTokensAndMint(
      path: BytesLike[],
      indexPool: string,
      minPoolAmountOut: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swapExactTokensForETH(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      path: BytesLike[],
      to: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swapExactTokensForTokens(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      path: BytesLike[],
      to: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swapExactTokensForTokensAndMint(
      amountIn: BigNumberish,
      path: BytesLike[],
      indexPool: string,
      minPoolAmountOut: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swapTokensForAllTokensAndMintExact(
      indexPool: string,
      intermediaries: BytesLike[],
      poolAmountOut: BigNumberish,
      tokenIn: string,
      amountInMax: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swapTokensForExactETH(
      amountOut: BigNumberish,
      amountInMax: BigNumberish,
      path: BytesLike[],
      to: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swapTokensForExactTokens(
      amountOut: BigNumberish,
      amountInMax: BigNumberish,
      path: BytesLike[],
      to: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swapTokensForTokensAndMintExact(
      amountInMax: BigNumberish,
      path: BytesLike[],
      indexPool: string,
      poolAmountOut: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    uniswapFactory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    weth(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
